name: Flutter CI

on:
  push:
    branches:
      - '**'     # Run on all branches
  pull_request:
    branches:
      - '**'     # Run on all branches

jobs:
  build:
    name: Run Flutter app (catalogue_app)
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: catalogue_app

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Install Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.0'   # adapt to your version
          channel: 'stable'

      # 3️⃣ Verify Flutter installation
      - name: Check Flutter version
        run: flutter --version

      # 4️⃣ Install project dependencies
      - name: Get dependencies
        run: flutter pub get

      # 5️⃣ Analyze code for errors
      - name: Analyze code
        run: flutter analyze

      # 6️⃣ Run tests (if any)
      - name: Run tests
        run: flutter test

      # 7️⃣ Build Android APK (optional)
      - name: Build APK
        run: flutter build apk --debug
